const classes = [
  "Algebra I",
  "Algebra II",
  "American Sign Language",
  "Band",
  "Biology",
  "Chemistry",
  "Choir",
  "Computer Science",
  "Creative Writing",
  "Culinary",
  "Debate",
  "Digital Design",
  "Early Childhood Development",
  "Earth Science",
  "English I",
  "English II",
  "English Language and Composition",
  "English Literature",
  "Environmental Science",
  "French I",
  "French II",
  "Geometry",
  "Global Perspectives",
  "Gymnastics",
  "Information Technology",
  "Law",
  "Macroeconomics",
  "Marine Science",
  "Microeconomics",
  "Orchestra",
  "Personal Finance",
  "Physics",
  "Pre-Calculus",
  "Psychology",
  "Research",
  "Seminar",
  "Spanish I",
  "Spanish II",
  "Weight Training",
  "World History",
];

const constants = {};
constants.classes = classes;

module.exports = constants;
